[build]
  command = "bundle exec jekyll build"
  publish = "_site"


[dev]
  targetPort = 0  # Disable proxying to a framework dev server

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
