[build]
  publish = "."  # Keep as "." if your index.html and admin folder are in the root
  command = ""   # No build command needed for plain static site

[dev]
  targetPort = 0  # Disable proxying to a framework dev server

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
